"""
export_variants.py -- export variants to .pte and generate the firmware headers.

    python3 python/export_variants.py --variant B   # the one command you run in class
    python3 python/export_variants.py --all         # every pte/variant_*.pte, no headers

--variant X does three things:
  1. exports checkpoints/variant_X.pt through ExecuTorch
     (torch.export -> to_edge -> to_executorch) to pte/variant_X.pte;
  2. writes generated/model_pte.h: the .pte as an aligned const byte array
     (the firmware embeds it in Flash), plus the variant ID and the host-side
     PyTorch predictions for the 10 test images;
  3. writes generated/test_images.h: 10 fixed Fashion-MNIST test images, the
     first of each class, already padded and normalized.

Then rebuild and flash the firmware (see ../README.md).

The export is plain fp32 through ExecuTorch's portable kernels, no backend
delegation and no quantization -- the same flow as the memory-budgeting
activity's executorch_memory_check.py.
"""

import argparse
import os

import torch
import executorch.exir as exir

from data import CLASS_NAMES, load_tensors
from model import (GENERATED_DIR, PTE_DIR, VARIANT_DESCRIPTIONS, VARIANTS,
                   load_variant, pte_path)

N_TEST_IMAGES = 10


def export_program(model: torch.nn.Module):
    """Returns the ExecutorchProgramManager (its .buffer is the .pte bytes)."""
    ep = torch.export.export(model.eval(), (torch.zeros(1, 1, 32, 32),))
    return exir.to_edge(ep).to_executorch()


def program_ops(prog) -> list:
    plan = prog.executorch_program.execution_plan[0]
    return sorted(f"{op.name}.{op.overload}" for op in plan.operators)


def planned_bytes(prog) -> int:
    """Size of the memory-planned activation arena (the firmware's
    planned_pool must be at least this). Index 0 of non_const_buffer_sizes
    is reserved; the arena is the rest."""
    plan = prog.executorch_program.execution_plan[0]
    return sum(plan.non_const_buffer_sizes)


def test_images():
    """The first test-set image of each class, in class order."""
    _, _, (x_test, y_test) = load_tensors()
    idx = [int((y_test == c).nonzero()[0]) for c in range(N_TEST_IMAGES)]
    return x_test[idx], y_test[idx]


def c_bytes(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",")
    return "\n".join(lines)


def write_model_header(variant: str, pte: bytes, host_preds):
    path = os.path.join(GENERATED_DIR, "model_pte.h")
    with open(path, "w") as f:
        f.write(f"""/* Generated by python/export_variants.py --variant {variant}. Do not edit. */
#pragma once
#include <stdint.h>

#define MODEL_VARIANT      "{variant}"
#define MODEL_DESCRIPTION  "{VARIANT_DESCRIPTIONS[variant]}"

/* PyTorch's predicted class for each image in test_images.h, computed on
 * the laptop from the same checkpoint. The firmware compares its own
 * predictions against these as an export sanity check. */
static const uint8_t host_predictions[{len(host_preds)}] = {{ {", ".join(str(p) for p in host_preds)} }};

/* ExecuTorch's FlatBuffer parser needs the program aligned to
 * alignof(std::max_align_t); a plain char array has no such guarantee. */
__attribute__((aligned(16))) static const unsigned char model_pte[] = {{
{c_bytes(pte)}
}};
static const unsigned int model_pte_len = {len(pte)};
""")
    return path


def write_test_images_header(x: torch.Tensor, y: torch.Tensor):
    path = os.path.join(GENERATED_DIR, "test_images.h")
    rows = []
    for i in range(len(x)):
        vals = x[i].flatten().tolist()
        body = ",\n".join(
            "        " + ", ".join(f"{v:.8g}f" for v in vals[j:j + 8])
            for j in range(0, len(vals), 8))
        rows.append(f"    {{ /* {i}: {CLASS_NAMES[int(y[i])]} */\n{body}\n    }}")
    names = ", ".join(f'"{n}"' for n in CLASS_NAMES)
    image_rows = ",\n".join(rows)  # no backslashes inside f-strings before Python 3.12
    with open(path, "w") as f:
        f.write(f"""/* Generated by python/export_variants.py. Do not edit.
 * The first Fashion-MNIST test image of each class, zero-padded to 32x32
 * and normalized exactly as in training (see python/data.py). */
#pragma once
#include <stdint.h>

#define N_TEST_IMAGES {len(x)}

static const char *const class_names[10] = {{ {names} }};

static const uint8_t test_labels[N_TEST_IMAGES] = {{ {", ".join(str(int(v)) for v in y)} }};

static const float test_images[N_TEST_IMAGES][32 * 32] = {{
{image_rows}
}};
""")
    return path


def export_variant(variant: str):
    model = load_variant(variant)
    prog = export_program(model)
    os.makedirs(PTE_DIR, exist_ok=True)
    with open(pte_path(variant), "wb") as f:
        f.write(prog.buffer)
    return model, prog


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--variant", choices=VARIANTS)
    g.add_argument("--all", action="store_true")
    args = ap.parse_args()

    for v in (VARIANTS if args.all else [args.variant]):
        model, prog = export_variant(v)
        print(f"[{v}] {pte_path(v)}: {len(prog.buffer)} bytes, "
              f"planned arena {planned_bytes(prog)} bytes")
        print(f"[{v}] ops: {', '.join(program_ops(prog))}")

    if args.all:
        return

    x, y = test_images()
    with torch.no_grad():
        preds = model(x).argmax(1).tolist()
    os.makedirs(GENERATED_DIR, exist_ok=True)
    print(f"[{args.variant}] wrote {write_model_header(args.variant, prog.buffer, preds)}")
    print(f"[{args.variant}] wrote {write_test_images_header(x, y)}")
    print(f"[{args.variant}] host predictions: {preds}  (labels {y.tolist()})")
    print("Now rebuild and flash: cmake --build --preset stm32 --target flash")


if __name__ == "__main__":
    main()
