"""
export_mlp.py -- export the teacher or a student to .pte for the board
(Part 5, optional) and generate the firmware headers.

    python3 python/export_mlp.py --model 3c --precision int8
    python3 python/export_mlp.py --model teacher --precision int8
    python3 python/export_mlp.py --model teacher --precision fp32   # see Part 5, Step 3

--model picks a checkpoint:
    teacher   checkpoints/teacher_lenet300100.pt (provided)
    3a ... 3d checkpoints/student_<cfg>.pt, the seed-0 student of that
              Part 3 configuration (part3_low_data.py saves them)

int8 is the quantization activity's flow, unchanged except for the input
shape: PT2E post-training quantization with ExecuTorch's CortexMQuantizer,
calibrated on the first 200 train_full images, then lowered so each
Linear (+ ReLU) runs as one CMSIS-NN cortex_m::quantized_linear op. fp32 is
torch.export -> to_edge -> to_executorch with portable kernels.

Each run writes pte/<build>.pte, generated/model_pte.h,
generated/test_images.h (the 200 embedded MNIST test images, uint8, 784 B
each) and results/host_<build>.json (the laptop's predictions, which the
firmware and compare_preds.py check the board against).
"""

import argparse
import json
import os

import torch
import executorch.exir as exir
from executorch.exir import EdgeCompileConfig, ExecutorchBackendConfig, to_edge

# Importing these registers the cortex_m:: ops with PyTorch.
import executorch.backends.cortex_m.ops.operators  # noqa: F401
from executorch.backends.cortex_m.passes.cortex_m_pass_manager import CortexMPassManager
from executorch.backends.cortex_m.quantizer.quantizer import CortexMQuantizer
from torchao.quantization.pt2e.quantize_pt2e import convert_pt2e, prepare_pt2e

from data import eval_set, pixel_lut, splits
from models import (CHECKPOINT_DIR, GENERATED_DIR, PTE_DIR, RESULTS_DIR, LeNet300100,
                    StudentMLP, count_params, load_teacher)

MODELS = ["teacher", "3a", "3b", "3c", "3d"]
DESCRIPTIONS = {
    "teacher": "teacher LeNet-300-100",
    "3a": "student 784-30-10, 1k labels, CE",
    "3b": "student 784-30-10, 1k labels, KD",
    "3c": "student 784-30-10, 1k labels + 54k unlabeled, KD",
    "3d": "student 784-30-10, 55k labels, CE",
}
EXAMPLE = (torch.zeros(1, 784),)


def load_model(name):
    if name == "teacher":
        return load_teacher()
    m = StudentMLP()
    path = os.path.join(CHECKPOINT_DIR, f"student_{name}.pt")
    if not os.path.exists(path):
        raise SystemExit(f"{path} is missing: run python3 python/part3_low_data.py first")
    m.load_state_dict(torch.load(path, map_location="cpu"))
    return m.eval()


def export_fp32(model):
    return exir.to_edge(torch.export.export(model, EXAMPLE)).to_executorch()


def export_int8(model, calib):
    gm = torch.export.export(model, EXAMPLE).module()
    prepared = prepare_pt2e(gm, CortexMQuantizer())
    with torch.no_grad():
        prepared(calib)
    converted = convert_pt2e(prepared)
    config = EdgeCompileConfig(preserve_ops=[torch.ops.aten.linear.default],
                               _check_ir_validity=False)
    epm = to_edge(torch.export.export(converted, EXAMPLE), compile_config=config)
    epm._edge_programs["forward"] = CortexMPassManager(epm.exported_program()).transform()
    prog = epm.to_executorch(config=ExecutorchBackendConfig(extract_delegate_segments=False))
    return converted, prog


def planned_bytes(prog):
    return sum(prog.executorch_program.execution_plan[0].non_const_buffer_sizes)


def instruction_names(prog):
    plan = prog.executorch_program.execution_plan[0]
    names = []
    for ins in plan.chains[0].instructions:
        args = ins.instr_args
        if hasattr(args, "op_index"):
            names.append(plan.operators[args.op_index].name)
        else:
            names.append(type(args).__name__.replace("Arguments", "").lower())
    return names


def c_bytes(data, per_line=12, indent="    "):
    return "\n".join(indent + ", ".join(f"0x{b:02x}" for b in data[i:i + per_line]) + ","
                     for i in range(0, len(data), per_line))


def write_headers(build, description, prog, host_preds, idx, u8, labels):
    instr = instruction_names(prog)
    names = ",\n".join(f'    "{n}"' for n in instr)
    with open(os.path.join(GENERATED_DIR, "model_pte.h"), "w") as f:
        f.write(f"""/* Generated by python/export_mlp.py. Do not edit. */
#pragma once
#include <stdint.h>

#define MODEL_BUILD        "{build}"
#define MODEL_DESCRIPTION  "{description}"

/* The laptop's prediction for each embedded test image. */
static const uint8_t host_predictions[{len(host_preds)}] = {{
    {", ".join(str(p) for p in host_preds)}
}};

#define N_INSTRUCTIONS {len(instr)}
static const char *const instruction_names[N_INSTRUCTIONS] = {{
{names}
}};

/* ExecuTorch's FlatBuffer parser needs the program 16-byte aligned. */
__attribute__((aligned(16))) static const unsigned char model_pte[] = {{
{c_bytes(prog.buffer)}
}};
static const unsigned int model_pte_len = {len(prog.buffer)};
""")
    lut = pixel_lut().tolist()
    lut_rows = ",\n".join("    " + ", ".join(f"{v:.9g}f" for v in lut[i:i + 8]) for i in range(0, 256, 8))
    rows = ",\n".join(f"    {{ /* {i}: test[{idx[i]}], digit {int(labels[i])} */\n"
                      + c_bytes(bytes(u8[i].tobytes()), 28, "        ") + "\n    }"
                      for i in range(len(u8)))
    with open(os.path.join(GENERATED_DIR, "test_images.h"), "w") as f:
        f.write(f"""/* Generated by python/export_mlp.py. Do not edit.
 * 200 MNIST test images (20 per digit, fixed seed; python/data.py
 * eval_set()), 28x28 flattened, stored as raw uint8 pixels. */
#pragma once
#include <stdint.h>

#define N_TEST_IMAGES {len(u8)}
#define N_PIXELS      784

static const uint8_t test_labels[N_TEST_IMAGES] = {{
    {", ".join(str(int(v)) for v in labels)}
}};

/* pixel_lut[p] = (p / 255 - MEAN) / STD, computed by PyTorch in float32. */
static const float pixel_lut[256] = {{
{lut_rows}
}};

static const uint8_t test_images[N_TEST_IMAGES][N_PIXELS] = {{
{rows}
}};
""")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--model", choices=MODELS, required=True)
    ap.add_argument("--precision", choices=["fp32", "int8"], required=True)
    args = ap.parse_args()

    build = f"{args.model}-{args.precision}"
    model = load_model(args.model)
    idx, u8, labels, x_eval = eval_set()
    if args.precision == "fp32":
        prog = export_fp32(model)
        with torch.no_grad():
            logits = model(x_eval)
    else:
        calib = splits()["train_full"][0][:200]
        converted, prog = export_int8(model, calib)
        with torch.no_grad():
            logits = converted(x_eval)
    preds = logits.argmax(1).tolist()
    description = f"{DESCRIPTIONS[args.model]}, {args.precision}"

    for d in (PTE_DIR, GENERATED_DIR, RESULTS_DIR):
        os.makedirs(d, exist_ok=True)
    with open(os.path.join(PTE_DIR, f"{build}.pte"), "wb") as f:
        f.write(prog.buffer)
    write_headers(build, description, prog, preds, idx, u8, labels)
    with open(os.path.join(RESULTS_DIR, f"host_{build}.json"), "w") as f:
        json.dump({"build": build, "description": description, "test_indices": [int(i) for i in idx],
                   "labels": labels.tolist(), "host_preds": preds,
                   "host_logits": [[round(v, 4) for v in r] for r in logits.tolist()]}, f)

    plan = prog.executorch_program.execution_plan[0]
    ops = sorted(f"{op.name}.{op.overload}" for op in plan.operators)
    acc = sum(p == int(l) for p, l in zip(preds, labels)) / len(preds)
    print(f"[{build}] {description}: {count_params(model)} parameters")
    print(f"[{build}] .pte {len(prog.buffer)} bytes, planned arena {planned_bytes(prog)} bytes")
    print(f"[{build}] ops: {', '.join(ops)}")
    print(f"[{build}] host accuracy on the 200 embedded images: {acc:.3f}")
    print("Now rebuild and flash: cmake --build --preset stm32 --target flash")


if __name__ == "__main__":
    main()
