"""
export_model.py -- export one build to .pte and generate the firmware headers.

    python3 python/export_model.py --variant A --precision fp32
    python3 python/export_model.py --variant A --precision int8
    python3 python/export_model.py --variant A --precision int8 --order pool-relu

A build is a variant (A or C) at a precision (fp32 or int8). Each run:
  1. exports the build to pte/<build>.pte
       fp32: torch.export -> to_edge -> to_executorch (portable kernels),
             exactly as in the pruning lab
       int8: PTQ with CortexMQuantizer, calibrated on --calib-n training
             images, then lowered to CMSIS-NN ops (see quantize.py)
  2. writes generated/model_pte.h: the .pte as an aligned byte array, the
     host's predictions for the embedded test images, and the name of each
     instruction (for the firmware's per-op profile)
  3. writes generated/test_images.h: the 200 fixed test images (uint8,
     32x32, 20 per class) and the uint8 -> float lookup table
  4. writes results/host_<build>.json: the host's predictions and logits for
     all 200 images, which compare_preds.py checks the board against

Then rebuild and flash the firmware (scripts/run_build.sh does all of it).

The host predictions for an int8 build come from the convert_pt2e model:
PyTorch running the quantize/dequantize graph in floating point. The board
runs the CMSIS-NN integer kernels. They should agree on nearly every image.

--order: the pruning lab's Model B2 pools before its ReLU, which saves
SRAM in fp32. The default here keeps that order for fp32 and uses
conv -> ReLU -> pool for int8 (same weights, same function). Pass
--order pool-relu with --precision int8 to see why (handout Part A, Step 3).

Calibration flags (handout Part B; the defaults are what Part A uses):
  --calib-n N            number of calibration images (default 200)
  --calib-class K        calibrate on images of class K only
  --calib-no-normalize   skip (x - mean) / std on the calibration images
"""

import argparse
import json
import os

import torch

from data import CLASS_NAMES, N_EVAL, calibration_set, eval_set, pixel_lut
from model import (GENERATED_DIR, ORDERS, PTE_DIR, RESULTS_DIR, VARIANT_DESCRIPTIONS,
                   VARIANTS, build_name, load_variant)
from quantize import (CL, constant_tensors, export_fp32, export_int8, instruction_names,
                      planned_bytes, program_ops)

# The fp32 full-width model takes 1.4 s per inference on the board, so fp32
# builds classify only the first N_EVAL_FP32 images (an export check, not an
# accuracy measurement). int8 builds classify all 200.
N_EVAL_FP32 = 20


def c_bytes(data: bytes, per_line: int = 12) -> str:
    return "\n".join("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + per_line]) + ","
                     for i in range(0, len(data), per_line))


def write_model_header(build, description, pte, n_eval, host_preds, instr):
    path = os.path.join(GENERATED_DIR, "model_pte.h")
    names = ",\n".join(f'    "{n}"' for n in instr)
    with open(path, "w") as f:
        f.write(f"""/* Generated by python/export_model.py. Do not edit. */
#pragma once
#include <stdint.h>

#define MODEL_BUILD        "{build}"
#define MODEL_DESCRIPTION  "{description}"

/* The board classifies the first N_EVAL_RUN images of test_images.h. */
#define N_EVAL_RUN {n_eval}

/* The laptop's prediction for each of those images (for an int8 build, from
 * the convert_pt2e model). The firmware reports how often it agrees. */
static const uint8_t host_predictions[N_EVAL_RUN] = {{
    {", ".join(str(p) for p in host_preds[:n_eval])}
}};

/* One name per instruction, in execution order, for the per-op profile. */
#define N_INSTRUCTIONS {len(instr)}
static const char *const instruction_names[N_INSTRUCTIONS] = {{
{names}
}};

/* ExecuTorch's FlatBuffer parser needs the program aligned to
 * alignof(std::max_align_t); a plain char array has no such guarantee. */
__attribute__((aligned(16))) static const unsigned char model_pte[] = {{
{c_bytes(pte)}
}};
static const unsigned int model_pte_len = {len(pte)};
""")
    return path


def write_test_images_header(idx, u8, labels):
    path = os.path.join(GENERATED_DIR, "test_images.h")
    lut = pixel_lut().tolist()
    lut_rows = ",\n".join("    " + ", ".join(f"{v:.9g}f" for v in lut[i:i + 8])
                          for i in range(0, 256, 8))
    rows = []
    for i in range(len(u8)):
        rows.append(f"    {{ /* {i}: test[{idx[i]}], {CLASS_NAMES[int(labels[i])]} */\n"
                    + c_bytes(bytes(u8[i].tobytes()), per_line=32).replace("    0x", "        0x")
                    + "\n    }")
    names = ", ".join(f'"{n}"' for n in CLASS_NAMES)
    image_rows = ",\n".join(rows)
    with open(path, "w") as f:
        f.write(f"""/* Generated by python/export_model.py. Do not edit.
 * 200 Fashion-MNIST test images (20 per class, fixed seed; see
 * python/data.py eval_set()), zero-padded to 32x32, stored as raw uint8
 * pixels: 1 KiB each instead of 4 KiB as floats. */
#pragma once
#include <stdint.h>

#define N_TEST_IMAGES {len(u8)}

static const char *const class_names[10] = {{ {names} }};

static const uint8_t test_labels[N_TEST_IMAGES] = {{
    {", ".join(str(int(v)) for v in labels)}
}};

/* pixel_lut[p] = (p / 255 - MEAN) / STD, computed by PyTorch in float32, so
 * the board's input tensor is bit-for-bit the one the laptop used. */
static const float pixel_lut[256] = {{
{lut_rows}
}};

static const uint8_t test_images[N_TEST_IMAGES][32 * 32] = {{
{image_rows}
}};
""")
    return path


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--variant", choices=VARIANTS, required=True)
    ap.add_argument("--precision", choices=["fp32", "int8"], required=True)
    ap.add_argument("--order", choices=ORDERS,
                    help="default: pool-relu for fp32, relu-pool for int8")
    ap.add_argument("--calib-n", type=int, default=200)
    ap.add_argument("--calib-class", type=int, choices=range(10), metavar="K")
    ap.add_argument("--calib-no-normalize", action="store_true")
    ap.add_argument("--strip-unused", action="store_true",
                    help="int8: drop constants the lowered graph never reads")
    args = ap.parse_args()

    order = args.order or ("pool-relu" if args.precision == "fp32" else "relu-pool")
    build = build_name(args.variant, args.precision)
    model = load_variant(args.variant, order)
    idx, u8, labels, x_eval = eval_set()

    notes = [VARIANT_DESCRIPTIONS[args.variant], args.precision, order]
    if args.precision == "fp32":
        prog = export_fp32(model)
        with torch.no_grad():
            logits = model(x_eval)
        n_eval = N_EVAL_FP32
    else:
        calib = calibration_set(args.calib_n, args.calib_class, not args.calib_no_normalize)
        converted, prog = export_int8(model, calib, strip_unused=args.strip_unused)
        with torch.no_grad():
            logits = converted(x_eval.contiguous(memory_format=CL))
        n_eval = N_EVAL
        notes.append(f"calib {len(calib)}")
        if args.calib_class is not None:
            notes.append(f"class {args.calib_class} only")
        if args.calib_no_normalize:
            notes.append("NOT normalized")
        if args.strip_unused:
            notes.append("stripped")
    preds = logits.argmax(1).tolist()
    description = ", ".join(notes)

    os.makedirs(PTE_DIR, exist_ok=True)
    os.makedirs(GENERATED_DIR, exist_ok=True)
    os.makedirs(RESULTS_DIR, exist_ok=True)
    pte_file = os.path.join(PTE_DIR, f"{build}.pte")
    with open(pte_file, "wb") as f:
        f.write(prog.buffer)

    instr = instruction_names(prog)
    write_model_header(build, description, prog.buffer, n_eval, preds, instr)
    write_test_images_header(idx, u8, labels)
    with open(os.path.join(RESULTS_DIR, f"host_{build}.json"), "w") as f:
        json.dump({"build": build, "description": description,
                   "test_indices": [int(i) for i in idx],
                   "labels": labels.tolist(), "host_preds": preds,
                   "host_logits": [[round(v, 4) for v in row] for row in logits.tolist()]}, f)

    const_bytes = sum(c[3] for c in constant_tensors(prog))
    acc = sum(p == int(l) for p, l in zip(preds, labels)) / len(preds)
    print(f"[{build}] {description}")
    print(f"[{build}] {pte_file}: {len(prog.buffer)} bytes "
          f"({const_bytes} in constant tensors), planned arena {planned_bytes(prog)} bytes")
    print(f"[{build}] ops: {', '.join(program_ops(prog))}")
    print(f"[{build}] host accuracy on the 200 embedded images: {acc:.3f}")
    print(f"[{build}] wrote generated/model_pte.h, generated/test_images.h, results/host_{build}.json")
    print("Now rebuild and flash: cmake --build --preset stm32 --target flash")


if __name__ == "__main__":
    main()
